export {default as Header} from './Header/Header';
export {default as TopHeader} from './Header/TopHeader';
export {default as Nav} from './Navigation/Nav';
export {default as Sidebar} from './Sidebar/Sidebar';
export {default as Banner} from './Banner'
export {default as BestSeller} from './common/BestSeller';
export {default as Products} from './common/Products';
export {default as DealDaily} from './common/DealDaily';
export {default as Countdown} from './common/Countdown';
export {default as SelectQuantity} from './common/SelectQuantity';
export {default as Footer} from './Footer/Footer'
